# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: UniCube Documentations
site_author: Jean Nguyen
repo_name: Github
repo_url: https://github.com/unicubevn/documentation
edit_uri: 'docs/'
site_url: 'https://docs.unicube.vn'
theme:
  name: material
  logo: assets/logo.png
  font: false
  language: vi
  icon:
    logo: material/library
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.footer
    - search.share


  palette:
    - scheme: unicube
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: unicube
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: unicube
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - blog
#  - optimize
  - social
  - search
  - git-revision-date
#  - pdf-export:
#      combined: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

# Customization
extra:
  version:
    provider: mike
  alternate:
    - name: Vietnamese
      link: /vi/
      lang: vi
    - name: English
      link: /en/
      lang: en
  socials:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
extra_css:
  - https://fonts.cdnfonts.com/css/montserrat
  - https://fonts.cdnfonts.com/css/noto-mono
  - assets/stylesheets/extra.css
# Enabling permalinks on TOC
markdown_extensions:
  - smarty
  - toc:
      permalink: true
      separator: "_"
  - sane_lists
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
# Navigation with TOC (Table of Content)
nav:
  - Home: home/vi/index.md
  - Blog: blog/vi/index.md
  - Guides: guides/vi/index.md
  - About Us: home/vi/about.md
